package com.bootcamp.bank1.entity;

import java.io.Serializable;
import java.util.Date;

public class LocalCancelLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_cancel_log.tx_no
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    private String txNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_cancel_log.create_time
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_cancel_log.tx_no
     *
     * @return the value of local_cancel_log.tx_no
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    public String getTxNo() {
        return txNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_cancel_log.tx_no
     *
     * @param txNo the value for local_cancel_log.tx_no
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    public void setTxNo(String txNo) {
        this.txNo = txNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_cancel_log.create_time
     *
     * @return the value of local_cancel_log.create_time
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_cancel_log.create_time
     *
     * @param createTime the value for local_cancel_log.create_time
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}