package com.bootcamp.bank2.entity;

import java.io.Serializable;
import java.util.Date;

public class LocalTryLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_try_log.tx_no
     *
     * @mbg.generated Sun Nov 21 20:47:59 CST 2021
     */
    private String txNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_try_log.create_time
     *
     * @mbg.generated Sun Nov 21 20:47:59 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table local_try_log
     *
     * @mbg.generated Sun Nov 21 20:47:59 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_try_log.tx_no
     *
     * @return the value of local_try_log.tx_no
     *
     * @mbg.generated Sun Nov 21 20:47:59 CST 2021
     */
    public String getTxNo() {
        return txNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_try_log.tx_no
     *
     * @param txNo the value for local_try_log.tx_no
     *
     * @mbg.generated Sun Nov 21 20:47:59 CST 2021
     */
    public void setTxNo(String txNo) {
        this.txNo = txNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_try_log.create_time
     *
     * @return the value of local_try_log.create_time
     *
     * @mbg.generated Sun Nov 21 20:47:59 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_try_log.create_time
     *
     * @param createTime the value for local_try_log.create_time
     *
     * @mbg.generated Sun Nov 21 20:47:59 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}