package com.bootcamp.bank1.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Balance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.id
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.account_no
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    private String accountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.rmb
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    private BigDecimal rmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.frozen_rmb
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    private BigDecimal frozenRmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.dollar
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    private BigDecimal dollar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.frozen_dollar
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    private BigDecimal frozenDollar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table balance
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.id
     *
     * @return the value of balance.id
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.id
     *
     * @param id the value for balance.id
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.account_no
     *
     * @return the value of balance.account_no
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.account_no
     *
     * @param accountNo the value for balance.account_no
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.rmb
     *
     * @return the value of balance.rmb
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public BigDecimal getRmb() {
        return rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.rmb
     *
     * @param rmb the value for balance.rmb
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public void setRmb(BigDecimal rmb) {
        this.rmb = rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.frozen_rmb
     *
     * @return the value of balance.frozen_rmb
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public BigDecimal getFrozenRmb() {
        return frozenRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.frozen_rmb
     *
     * @param frozenRmb the value for balance.frozen_rmb
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public void setFrozenRmb(BigDecimal frozenRmb) {
        this.frozenRmb = frozenRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.dollar
     *
     * @return the value of balance.dollar
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public BigDecimal getDollar() {
        return dollar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.dollar
     *
     * @param dollar the value for balance.dollar
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public void setDollar(BigDecimal dollar) {
        this.dollar = dollar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.frozen_dollar
     *
     * @return the value of balance.frozen_dollar
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public BigDecimal getFrozenDollar() {
        return frozenDollar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.frozen_dollar
     *
     * @param frozenDollar the value for balance.frozen_dollar
     *
     * @mbg.generated Sun Nov 21 10:25:03 CST 2021
     */
    public void setFrozenDollar(BigDecimal frozenDollar) {
        this.frozenDollar = frozenDollar;
    }
}