package com.bootcamp.bank1.mapper;

import com.bootcamp.bank1.entity.AccountInfo;
import com.bootcamp.bank1.entity.AccountInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    long countByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int deleteByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int insert(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int insertSelective(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    List<AccountInfo> selectByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int updateByExample(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    int subtractAccountBalance(@Param("accountNo") String accountNo, @Param("amount") Double amount);

    int addAccountBalance(@Param("accountNo") String accountNo, @Param("amount") Double amount);
}