package com.bootcamp.bank2.mapper;

import com.bootcamp.bank2.entity.LocalCancelLog;
import com.bootcamp.bank2.entity.LocalCancelLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalCancelLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    long countByExample(LocalCancelLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int deleteByExample(LocalCancelLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int insert(LocalCancelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int insertSelective(LocalCancelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    List<LocalCancelLog> selectByExample(LocalCancelLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") LocalCancelLog record, @Param("example") LocalCancelLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_cancel_log
     *
     * @mbg.generated Mon Nov 08 17:21:28 CST 2021
     */
    int updateByExample(@Param("record") LocalCancelLog record, @Param("example") LocalCancelLogExample example);

    int isExistCancel(@Param("txNo") String txNo);
}