package com.bootcamp.cache09.mapper;

import com.bootcamp.cache09.entity.BsOrder;
import com.bootcamp.cache09.entity.BsOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_order
     *
     * @mbg.generated Fri Dec 03 16:09:32 CST 2021
     */
    long countByExample(BsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_order
     *
     * @mbg.generated Fri Dec 03 16:09:32 CST 2021
     */
    int deleteByExample(BsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_order
     *
     * @mbg.generated Fri Dec 03 16:09:32 CST 2021
     */
    int insert(BsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_order
     *
     * @mbg.generated Fri Dec 03 16:09:32 CST 2021
     */
    int insertSelective(BsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_order
     *
     * @mbg.generated Fri Dec 03 16:09:32 CST 2021
     */
    List<BsOrder> selectByExample(BsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_order
     *
     * @mbg.generated Fri Dec 03 16:09:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") BsOrder record, @Param("example") BsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_order
     *
     * @mbg.generated Fri Dec 03 16:09:32 CST 2021
     */
    int updateByExample(@Param("record") BsOrder record, @Param("example") BsOrderExample example);
}